Core/task 228 development environment docker compose
dexpresso-protocol/core pull request #334
Opened 2023-03-11 09:49 UTC by isaac-fibonacci

1. I added docker-compose.local.yml to manage the containers we need (backend code, postgres, redis).
2. I added nodemon configs to the package.json file
3. I added dependency packages to package.json

**Note**: We share all the code with the container in this docker-compose. After each file change in the src directory, the nodemon package is called, and the recompile container contains the code.
##Checklist
- [ ] Make Sure all containers run correctly and get an IP for each of them
- [ ] Make sure to recompile the code after each file change and your changes will take effect

- [ ] All Merge Request pipelines should be passed.
- [ ] Could you ensure all the necessary changes are correct?
- [ ] Make sure no change is missing (all necessary changes are made).
- [ ] Merge Request should contain only changes for one purpose (one feature, bug, or refactoring).
- [ ] All necessary unit tests are written.
- [ ] Critical changes should be tested locally (or on staging).

2023-03-11 09:57 UTC, FlokiBB approved these changes

2023-03-13 19:03 UTC, FlokiBB requested changes

2023-03-13 19:03 UTC, FlokiBB commented on ts-version/.sequelizerc
> -require('dotenv').config('./.env');
why our env in sequlize is 
'env': 'development'

for both development and production ?

2023-03-13 19:04 UTC, FlokiBB commented
@isaac-fibonacci did you check rebuild feature on file change?

2023-03-13 20:22 UTC, isaac-fibonacci commented on ts-version/.sequelizerc
> -require('dotenv').config('./.env');
Done

2023-03-13 20:23 UTC, isaac-fibonacci commented on ts-version/localEnv
> +------------------------------------------------------------------------
Done

2023-03-14 13:14 UTC, merged