Core/ts version task 427 event name structure
dexpresso-protocol/core pull request #458
Opened 2023-05-03 09:16 UTC by franken5tein

## What does this MR do?

## Check list  

- [ ] All Merge Request pipelines should be passed.
- [ ] Make sure all the changes are necessary and correct.
- [ ] Make sure no needed change missing (all necessary changes are made).
- [ ] Merge Request should contains only changes for one purpose (one feature or bug or refactoring).
- [ ] All necessary unit tests are written.
- [ ] Critical changes should be tested locally (or on staging).

2023-05-09 23:49 UTC, GreatGaryCooper requested changes

2023-05-09 23:49 UTC, GreatGaryCooper commented on ts-version/src/data/database/postgres/repository/fill.adapter.ts
> +        Fill.notify(FillEventName.Updated, fill);
Just a comment, we can omit the `Name` part and let it just be `FillEvent.Updated`.

2023-05-09 23:49 UTC, GreatGaryCooper commented on ts-version/src/data/price-api/ccxt.ts
> +        PriceAPI.notify(StatusEventName.Updated, marketStats);
It should be `StatsEvent.Updated`, not `StatusEven.Updated`

2023-05-09 23:49 UTC, GreatGaryCooper commented on ts-version/src/domain/entities/fill.entity.ts
> +    Fill.notify(FillEventName.Created, fill);
This field used to be `fill_creating`, but it is `fill_created`, is there a reason for it?
Have we changed the logic?

2023-05-09 23:49 UTC, GreatGaryCooper commented on ts-version/src/domain/entities/order/order.entity.ts
> +    Order.notify(OrderEventName.Updating, order);
This used to be `order_creating`, but now it is `order_updating`, is it on purpose?

2023-05-09 23:49 UTC, GreatGaryCooper commented on ts-version/src/domain/types/event.type.ts
> +enum StatusEventName {
As per the comment above, this should be `Stats`, not `Status`

2023-05-17 12:59 UTC, franken5tein commented on ts-version/src/data/database/postgres/repository/fill.adapter.ts
> +        Fill.notify(FillEventName.Updated, fill);
Done!

2023-05-17 13:00 UTC, franken5tein commented on ts-version/src/data/price-api/ccxt.ts
> +        PriceAPI.notify(StatusEventName.Updated, marketStats);
Done!

2023-05-17 13:00 UTC, franken5tein commented on ts-version/src/domain/types/event.type.ts
> +enum StatusEventName {
Done!

2023-05-19 10:16 UTC, GreatGaryCooper approved these changes
LGTM

2023-05-20 14:58 UTC, hypersolo commented on ts-version/src/presentation/http/middlewares/authentication.ts
> +declare global {
move this to typing directory

2023-05-20 14:59 UTC, hypersolo commented
jwt-payload-validator middleware is not added in GET user/fills endpoint

2023-05-21 17:35 UTC, merged