test: add all test scenarios for unavailable balance api
dexpresso-protocol/core pull request #597
Opened 2023-07-11 20:07 UTC by isaac-fibonacci

## What does this MR do?

add all test scenarios for unavailable balance API

## Check list  

- [ X] All Merge Request pipelines should be passed.
- [X] Make sure all the changes are necessary and correct.
- [X] Make sure no needed change missing (all necessary changes are made).
- [X] Merge Request should contains only changes for one purpose (one feature or bug or refactoring).
- [X] All necessary unit tests are written.
- [X] Critical changes should be tested locally (or on staging).

2023-07-13 11:56 UTC, WilliamHawkingStephen requested changes
- nice one uncle :+1: 

suggestion: 
i think maybe its better to check status code responses in all test case scenarios

2023-07-13 11:59 UTC, franken5tein commented on src/test/e2e/get-unavailable-balance.e2e.test.ts
> +/* eslint-disable @typescript-eslint/no-non-null-assertion */
We should write these comments whenever necessary since the linter does not show a warning when we use them at the top of the file.

2023-07-13 12:03 UTC, WilliamHawkingStephen requested changes
- we can add avaiable balance test case scenario about sell and but order together

2023-07-13 12:50 UTC, franken5tein commented
Good job uncle 👌️

I think we should have available balance instead of unavailable balance.

2023-07-19 11:30 UTC, hypersolo approved these changes

2023-07-19 11:38 UTC, merged