task-213-add-rpc-provider-health-check
dexpresso-protocol/core pull request #619
Opened 2023-07-22 05:46 UTC by GreatGaryCooper

## What does this MR do?

## Check list  

- [x] All Merge Request pipelines should be passed.
- [x] Make sure all the changes are necessary and correct.
- [x] Make sure no needed change missing (all necessary changes are made).
- [x] Merge Request should contains only changes for one purpose (one feature or bug or refactoring).
- [x] All necessary unit tests are written.
- [x] Critical changes should be tested locally (or on staging).

2023-07-22 06:38 UTC, WilliamHawkingStephen approved these changes

2023-07-22 08:41 UTC, hypersolo requested changes

2023-07-22 08:41 UTC, hypersolo commented on src/utils/config/providers.ts
> +    await Promise.all(
in getBlockNumber function we get an rpc provider randomly and call getBlockNumber.
by checking health this way, we don't checkk all providers.

2023-07-29 06:36 UTC, GreatGaryCooper commented on src/utils/config/providers.ts
> +    await Promise.all(
Fixed, can you take a look?

2023-07-29 16:42 UTC, hypersolo commented on src/utils/config/providers.ts
> +      new Evm(
by calling evm constructor directly, we don't need Ethereum and Arbitrum classes anymore. let's delete them in this PR :love_letter:

2023-07-29 16:42 UTC, hypersolo commented on src/utils/config/providers.ts
> +    for (const provider of this.providers.values()) {
isn't it better to use Promise.all here?

2023-07-29 16:42 UTC, hypersolo commented on src/test/e2e/cancel-order.e2e.test.ts
> +    const getBlockNumberSpies = providers.getProviders().map((provider) =>
do we need these mocks in test files? i mean after we separate ping from start, we don't have to mock getBlockNumber function.

2023-07-31 01:42 UTC, GreatGaryCooper commented on src/utils/config/providers.ts
> +      new Evm(
Deleted, thanks 🙏🏻 🌹

2023-07-31 01:46 UTC, GreatGaryCooper commented on src/utils/config/providers.ts
> +    for (const provider of this.providers.values()) {
Changed, thanks mate 👍🏻

2023-07-31 01:51 UTC, GreatGaryCooper commented on src/test/e2e/cancel-order.e2e.test.ts
> +    const getBlockNumberSpies = providers.getProviders().map((provider) =>
Thanks for the report, removed 👍🏻

2023-07-31 08:01 UTC, hypersolo commented on src/utils/config/providers.ts
> +    await Promise.all(
Thanks buddy :love_you_gesture:

2023-07-31 08:01 UTC, hypersolo commented on src/utils/config/providers.ts
> +      new Evm(
:love_letter:

2023-07-31 08:02 UTC, hypersolo commented on src/test/e2e/cancel-order.e2e.test.ts
> +    const getBlockNumberSpies = providers.getProviders().map((provider) =>
noice :cupid:

2023-07-31 08:03 UTC, hypersolo commented on src/utils/config/providers.ts
> +    for (const provider of this.providers.values()) {
:heart:

2023-07-31 08:03 UTC, hypersolo approved these changes

2023-07-31 08:03 UTC, merged