Core/ts version task 209 market order e2e test
dexpresso-protocol/core pull request #637
Opened 2023-07-25 14:32 UTC by franken5tein

## What does this MR do?

Added market order e2e test

## Check list  

- [x] All Merge Request pipelines should be passed.
- [x] Make sure all the changes are necessary and correct.
- [x] Make sure no needed change missing (all necessary changes are made).
- [x] Merge Request should contains only changes for one purpose (one feature or bug or refactoring).
- [x] All necessary unit tests are written.
- [x] Critical changes should be tested locally (or on staging).

2023-07-26 07:43 UTC, hypersolo commented on src/test/e2e/market_order-e2e.test.ts
> +  it("Should rejected the order if the orderbook is empty", async () => {
should cancel ...

2023-07-26 07:43 UTC, hypersolo commented on src/test/e2e/market_order-e2e.test.ts
> +    // expect(createdOrder.quote_quantity).toEqual(createOrderPayload.market);
pointless comment bro :love_letter:

2023-07-26 07:43 UTC, hypersolo commented
do we cover the scenario in which we create some fills?

2023-07-26 15:13 UTC, GreatGaryCooper requested changes

2023-07-26 15:13 UTC, GreatGaryCooper commented on src/test/e2e/market_order-e2e.test.ts
> +    const invalidNetworkError = await getError<AxiosError>(async () => {
This should be `invalidMarketError`

2023-07-26 15:13 UTC, GreatGaryCooper commented on src/test/e2e/market_order-e2e.test.ts
> +    const invalidNetworkError = await getError<AxiosError>(async () => {
`invalidSignatureError`

2023-07-26 15:13 UTC, GreatGaryCooper commented on src/test/e2e/market_order-e2e.test.ts
> +    const invalidNetworkError = await getError<AxiosError>(async () => {
`invalidMaxFeeRatioError`

2023-07-26 15:13 UTC, GreatGaryCooper commented on src/test/e2e/market_order-e2e.test.ts
> +    const invalidNetworkError = await getError<AxiosError>(async () => {
`invalidPriceError`

2023-07-26 15:13 UTC, GreatGaryCooper commented on src/test/e2e/market_order-e2e.test.ts
> +    ).toContain("Invalid request parameters");
Also here if possible.

2023-07-30 11:29 UTC, franken5tein commented on src/test/e2e/market_order-e2e.test.ts
> +    const insufficientBalanceError = await getError<AxiosError>(async () => {
Done!

2023-07-30 11:29 UTC, franken5tein commented on src/test/e2e/market_order-e2e.test.ts
> +    const invalidNetworkError = await getError<AxiosError>(async () => {
Done!

2023-07-30 11:29 UTC, franken5tein commented on src/test/e2e/market_order-e2e.test.ts
> +    const invalidNetworkError = await getError<AxiosError>(async () => {
Done!

2023-07-30 11:29 UTC, franken5tein commented on src/test/e2e/market_order-e2e.test.ts
> +    const invalidNetworkError = await getError<AxiosError>(async () => {
Done!

2023-07-30 11:29 UTC, franken5tein commented on src/test/e2e/market_order-e2e.test.ts
> +    const invalidNetworkError = await getError<AxiosError>(async () => {
Done!

2023-07-30 11:30 UTC, franken5tein commented on src/test/e2e/market_order-e2e.test.ts
> +    const invalidNetworkError = await getError<AxiosError>(async () => {
Done!

2023-07-30 11:30 UTC, franken5tein commented on src/test/e2e/market_order-e2e.test.ts
> +    ).toContain("Invalid request parameters");
Done!

2023-07-30 11:30 UTC, franken5tein commented on src/test/e2e/market_order-e2e.test.ts
> +    ).toContain("Invalid request parameters");
Done!

2023-07-31 12:22 UTC, hypersolo approved these changes

2023-07-31 15:42 UTC, GreatGaryCooper approved these changes
Awesome bro, thanks 🌹

2023-07-31 15:58 UTC, merged